//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001_ProyectoDataTableAjaxCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECT_CRUD_ASPEntities3 : DbContext
    {
        public PROYECT_CRUD_ASPEntities3()
            : base("name=PROYECT_CRUD_ASPEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_categoria> tb_categoria { get; set; }
        public virtual DbSet<tb_producto> tb_producto { get; set; }
    }
}
