//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001_ProyectoDataTableAjaxCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        public int cod_producto { get; set; }
        public int cod_categoria { get; set; }
        public string descrip_prod { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<double> pventa { get; set; }
        public Nullable<System.DateTime> fecha_venc { get; set; }
        public bool activo { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
    }
}
